name: jdr_maker
description: Application de création de jeux de rôles
publish_to: "none"
version: 1.1.5

environment:
  sdk: ">=2.18.1 <3.3.2"

# Mise à jour des dépendances avec
# flutter pub upgrade --major-versions
#
# Installation d'une dépendance
# flutter pub add nom_dependance
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Rooting
  provider: ^6.0.3

  # Firebase Desktop
  firedart: ^0.9.0+1
  # DLC for using storage on desktop

  # Firebase Android
  firebase_core: ^2.8.0
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3

  # Better grid view
  flutter_staggered_grid_view: ^0.6.2

  # Support for modify windows version
  bitsdojo_window: ^0.1.5

  # Verify mail format
  email_validator: ^2.1.17

  # ID generator
  uuid: ^3.0.7

  # Get Local Time
  intl: ^0.17.0

  # Serveur Node
  socket_io_client: ^2.0.1
  googleapis: ^10.1.0

  # ???
  file_picker: ^5.2.5
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  flutter_dotenv: ^5.0.2
  gcloud: ^0.8.7
  googleapis_auth: ^1.4.0
  flutter_quill: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  win32: ^3.0.0

flutter:
  uses-material-design: true
  # Retirer des assets les dossiers vide ou n'existant pas sur votre branche
  assets:
    - assets/json/
    - assets/img/
    - .env
